In [8]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/natsu/miniconda3/lib/python3.10/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [9]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(312, tf.int32)
floating = tf.Variable(3.567, tf.float64)
# these are rank 0 tensors

In [10]:
rank1_tensor = tf.Variable(["Test"], tf.string)  # rank is 1
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)  # rank is 2

In [11]:
# to determine rank -
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
# to get shape of a tensor - which is basically number of elements in each dimension
rank2_tensor.shape

TensorShape([2, 2])

In [20]:
tensor1 = tf.ones([1,2,3])  # creates a tensor with shape [1,2,3] with all elements = 1
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshapes the tensor1 to the shape [2,3,1]

# check tensor3 variable syntax on google *reminder*
tensor3 = tf.reshape(tensor2, [3, -1])  #  -1 tells the tensor to calculate the size of the dimension in that place
                                        #  this will reshape the tensor to a [3,2] tensor
    
# The numer of elements in the reshaped tensor MUST match the number in the original (obviously)

In [21]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [22]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [26]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


In [27]:
# watch a video for tensor slicing pleaseeeeeeeeee = 0 
# as not done, change to 1 if done